name: covidart
description: An app on COVID-19 topic made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  country: ^2.0.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
